In [ ]:
#https://www.learnopencv.com/cnn-fully-convolutional-image-classification-with-tensorflow/
#https://www.youtube.com/watch?v=glmowUlqoYw&list=PLv8Cp2NvcY8DpVcsmOT71kymgMmcr59Mf&index=9&ab_channel=CodeWithAarohi
#https://pylessons.com/Keras-ResNet-tutorial/
#https://datascience-enthusiast.com/DL/Residual_Networks_v2.html
#https://cv-tricks.com/keras/understand-implement-resnets/
#https://codereview.stackexchange.com/questions/213371/a-simple-toy-resnet-model-and-its-implementation
#https://www.youtube.com/watch?v=6rXY1usgHcw&ab_channel=peacewazbd(zakir naik)


##############################################################################################
#in normal network we learn from Y but in Residual Network we learn from f(x) and our target 
#is to make f(x)=0 then only we can make input=output
##############################################################################################

In [ ]:
#the outermost dimension have 4 arrays that contains 3 arrays, each with 5 elements
c=np.zeros((4,3,5))
c

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
########################def read_image(file_path):
  #cv2.IMREAD_COLOR: It specifies to load a color image
  #cv2.imread() method loads an image from the specified file.
  ###########################img=cv2.imread(file_path,cv2.IMREAD_COLOR)
  #https://www.tutorialkart.com/opencv/python/opencv-python-resize-image/
  #(rows,cols) means desired size for the output image
  #interpolation=cv2.INTER_CUBIC: [optional] flag that interpolation over 8×8 pixel neighborhood
  ######################return cv2.resize(img,(rows,cols),interpolation=cv2.INTER_CUBIC)

In [ ]:
#2: 2 times the outermost dimension have 3 arrays that contains 4 arrays, each with 5 elements
c=np.zeros((2,3,4,5))
#print(c)
c[1,:]=1
c

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [ ]:
c=np.zeros((1,1,13))#or c=np.zeros((1,13))
c

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [ ]:
a=np.zeros((3,3))
a[1,:]=3
a

array([[0., 0., 0.],
       [3., 3., 3.],
       [0., 0., 0.]])

In [ ]:
a[1,1]

3.0

In [ ]:
a=np.zeros((1,5))
a

array([[0., 0., 0., 0., 0.]])

In [ ]:
#this is how enumerate works
x = ('apple', 'banana', 'cherry')
y = enumerate(x)

print(list(y))

[(0, 'apple'), (1, 'banana'), (2, 'cherry')]


In [ ]:
train_dir='/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/'
test_dir='/ResNet/MyDrive/cats_and_dogs_filtered/validation/'

In [ ]:
##this is how enumerate works in mydrive dataset
c=0
for j, image_file in enumerate(train_dir+i for i in os.listdir(train_dir)):
  print(j)
  print(image_file)
  c=c+1
  if(c>3):
    break


0
/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.100.jpg
1
/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.0.jpg
2
/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.10.jpg
3
/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.1.jpg


In [ ]:
X=np.zeros((2,rows,cols,channels),dtype=np.uint8)
X

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        ...,

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0,

In [ ]:
#def read_image(file_path):#############
  #cv2.IMREAD_COLOR: It specifies to load a color image
  #cv2.imread() method loads an image from the specified file.
  #img=cv2.imread(file_path,cv2.IMREAD_COLOR)###########
  #https://www.tutorialkart.com/opencv/python/opencv-python-resize-image/
  #(rows,cols) means desired size for the output image
  #interpolation=cv2.INTER_CUBIC: [optional] flag that interpolation over 8×8 pixel neighborhood
  #return cv2.resize(img,(rows,cols),interpolation=cv2.INTER_CUBIC)############

X[0,:]=read_image('/ResNet/MyDrive/cats_and_dogs_filtered/validation/cats/cat.2000.jpg')

In [ ]:
X

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        ...,

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0,

In [ ]:
#The eye() function is used to create a 2-D array with ones on the diagonal and zeros elsewhere.
a=np.eye(2,2)
print(a)
a=np.eye(2,3)
print('##################')
print(a)

[[1. 0.]
 [0. 1.]]
##################
[[1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
#Permute the dimensions of an array except that self is returned if self.ndim < 2.
a=np.array([[1,2,3],[4,5,6]])
print(a)
a=a.T
print(a)
a=(1,23)
a=a.reshape(-1)
print(a)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


AttributeError: ignored

In [ ]:
import numpy as np
nb_classes = 6
print(np.eye(6))
targets = np.array([[2, 3, 4, 0]]).reshape(-1)
print(targets)
one_hot_targets = np.eye(nb_classes)[targets]
print(one_hot_targets)
one_hot_targets_transpose = np.eye(nb_classes)[targets].T
print(one_hot_targets_transpose)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[2 3 4 0]
[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]


In [ ]:
def convert_onehot(y,c):
  y=np.eye(c)[y.reshape(-1)]
  return y

In [ ]:
a=np.array([[2,3,4,0]])
cal=convert_onehot(a,6)
print(cal)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [ ]:
#https://www.geeksforgeeks.org/random-seed-in-python/
#https://stackoverflow.com/questions/21494489/what-does-numpy-random-seed0-do

import random 
random.seed(0) 
# print a random number between 1 and 1000. 
print(random.randint(1, 1000)) 
# if you want to get the same random number again then, 
random.seed(0)  
print(random.randint(1, 1000)) 
# If seed function is not used 
# Gives totally unpredictable responses. 
print(random.randint(1, 1000)) 

865
865
395


In [ ]:
np.random.seed(0)
print(np.random.rand(4))
np.random.seed(0)
print(np.random.rand(4))

[0.5488135  0.71518937 0.60276338 0.54488318]
[0.5488135  0.71518937 0.60276338 0.54488318]


In [ ]:
np.random.seed(4)
print(np.random.rand(4))
np.random.seed(3)
print(np.random.rand(4))

[0.96702984 0.54723225 0.97268436 0.71481599]
[0.5507979  0.70814782 0.29090474 0.51082761]


In [ ]:
import os
import cv2
import numpy as np
from keras import layers
from keras.layers import Input, Add, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D, AveragePooling2D, MaxPooling2D
from keras.models import Model, load_model
from keras.initializers import glorot_uniform
from keras.utils import plot_model
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
import keras.backend as K
import tensorflow as tf

In [ ]:
rows = 64
cols = 64
channels = 3
classes = 2

In [ ]:
from google.colab import drive
drive.mount('/ResNet')


Mounted at /ResNet


In [ ]:
def read_image(file_path):
  img=cv2.imread(file_path)
  #print('read_image : ',file_path,img)
  return cv2.resize(img,(rows,cols),interpolation=cv2.INTER_CUBIC)
def prepare_data(images):
  m=len(images)
  X=np.zeros((m,rows,cols,channels),dtype=np.uint8)
  y=np.zeros((1,m),dtype=np.uint8)
  #print('prepare_data_images : ',images)
  for i,image_file in enumerate(images):
    #print('prepare_data : ',image_file,i)
    read_image(image_file)
    if('dog' in image_file.lower()):
      y[0,i]=1
    elif('cat' in image_file.lower()):
      y[0,i]=0
  return X,y

In [ ]:
train_dir='/ResNet/MyDrive/cats_and_dogs_filtered/train/'
test_dir='/ResNet/MyDrive/cats_and_dogs_filtered/validation/'
train_dir_dogs=os.path.join(train_dir,'dogs/')
train_dir_cats=os.path.join(train_dir,'cats/')
test_dir_dogs=os.path.join(test_dir,'dogs/')
test_dir_cats=os.path.join(test_dir,'cats/')

train_dogs_cats=[]
train_dogs_cats.append(train_dir_dogs)
train_dogs_cats.append(train_dir_cats)

test_dogs_cats=[]
test_dogs_cats.append(test_dir_dogs)
test_dogs_cats.append(test_dir_cats)

train_dogs_len=len(os.listdir(train_dir_dogs))
train_cats_len=len(os.listdir(train_dir_cats))
total_train=train_dogs_len+train_cats_len

test_dogs_len=len(os.listdir(test_dir_dogs))
test_cats_len=len(os.listdir(test_dir_cats))
total_test=test_dogs_len+test_cats_len

print('total train : ',total_train)
print('total test : ',total_test)

print(train_dogs_cats[0])
print(train_dogs_cats[1])
print(test_dogs_cats[0])
print(test_dogs_cats[1])

total train :  2000
total test :  1000
/ResNet/MyDrive/cats_and_dogs_filtered/train/dogs/
/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/
/ResNet/MyDrive/cats_and_dogs_filtered/validation/dogs/
/ResNet/MyDrive/cats_and_dogs_filtered/validation/cats/


In [ ]:
for i in range(0,len(train_dogs_cats)):
  train_images=[train_dogs_cats[i]+j for j in os.listdir(train_dogs_cats[i])]
print(train_images)


['/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.100.jpg', '/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.0.jpg', '/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.10.jpg', '/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.1.jpg', '/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.101.jpg', '/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.102.jpg', '/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.103.jpg', '/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.104.jpg', '/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.105.jpg', '/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.106.jpg', '/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.107.jpg', '/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.108.jpg', '/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.109.jpg', '/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.110.jpg', '/ResNet/MyDrive/cats_and_dogs_filtered/train/cats/cat.11.jpg', '/ResNet/MyDrive/cats_and_dogs

In [ ]:
#it requires some times(8 minutes)
train_set_x,train_set_y=prepare_data(train_images)



In [ ]:
print('train_set_x : ',train_set_x.shape)
print('train_set_y : ',train_set_y.shape)

train_set_x :  (1000, 64, 64, 3)
train_set_y :  (1, 1000)


In [ ]:
for i in range(0,len(test_dogs_cats)):
  test_images=[test_dogs_cats[i]+j for j in os.listdir(test_dogs_cats[i])]

In [ ]:
#t requires some times(4 minutes)
test_set_x,test_set_y=prepare_data(test_images)


In [ ]:
print('test_set_x : ',test_set_x.shape)
print('test_set_y : ',test_set_y.shape)


test_set_x :  (500, 64, 64, 3)
test_set_y :  (1, 500)


In [ ]:
x_train=train_set_x/255
x_test=test_set_x/255

In [ ]:
def convert_to_one_hot(y,c):
  yy=np.eye(c)
  #print(yy)
  r=y.reshape(-1).T
  #print(r.shape)
  yy=np.eye(c)[y.reshape(-1)].T

  return yy


In [ ]:
y_train=convert_to_one_hot(train_set_y,classes)
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [ ]:
y_train=convert_to_one_hot(train_set_y,classes).T
y_train

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [ ]:
y_test=convert_to_one_hot(test_set_y,classes).T
#y_test

In [ ]:
print('train_set_x : ',train_set_x.shape)
print('train_set_y : ',train_set_y.shape)
print('test_set_x : ',test_set_x.shape)
print('test_set_y : ',test_set_y.shape)
print('#################################')
print('x_train : ',x_train.shape)
print('x_test : ',x_test.shape)
print('y_train : ',y_train.shape)
print('y_test : ',y_test.shape)

train_set_x :  (1000, 64, 64, 3)
train_set_y :  (1, 1000)
test_set_x :  (500, 64, 64, 3)
test_set_y :  (1, 500)
#################################
x_train :  (1000, 64, 64, 3)
x_test :  (500, 64, 64, 3)
y_train :  (1000, 2)
y_test :  (500, 2)


In [ ]:
def identity_block(x,f,filters,stage,block):
  #defining name basis
  conv_name_base='res'+str(stage)+block+'_branch'
  bn_name_base='bn'+str(stage)+block+'_branch'
  #retrieve filter
  f1,f2,f3=filters
  #save the input value. it will be needed later to add back to the main path
  x_shortcut=x

  #first component of main path
  x=Conv2D(filters=f1,kernel_size=(1,1),strides=(1,1),padding='valid',
           name=conv_name_base+'2a',
           #The neural network needs to start with some weights and then iteratively update them 
           #to better values. The term kernel_initializer is a fancy term for which statistical 
           #distribution or function to use for initialising the weights.
           ##############################################
           #seed: A Python integer Used to seed the random generator.
           #seed: A Python integer An initializer created with a given seed will always produce 
           #the same random tensor for a given shape and dtype.
           kernel_initializer=glorot_uniform(seed=0))(x)
#If the dimension is [height, width, channel] then the axis is 3. The batch is not part of the input dimension.
  x=BatchNormalization(axis=3,name=bn_name_base+'2a')(x)
  x=Activation('relu')(x)

  #second component of main path
  x=Conv2D(filters=f2,kernel_size=(f,f),strides=(1,1),padding='same',
           #if padding='valid dei tobe error pabo cause x & x_shortcut size same hobe na
           #so x & x_shortcut size same korar jonno########## padding='same' dibo############
           #brief #https://www.nuomiphp.com/eplan/en/21119.html
           name=conv_name_base+'2b',
           kernel_initializer=glorot_uniform(seed=0))(x)
  x=BatchNormalization(axis=3,name=bn_name_base+'2b')(x)
  x=Activation('relu')(x)

  #third component of main path
  x=Conv2D(filters=f3,kernel_size=(1,1),strides=(1,1),padding='valid',
           name=conv_name_base+'2c',
           kernel_initializer=glorot_uniform(seed=0))(x)
  x=BatchNormalization(axis=3,name=bn_name_base+'2c')(x)

  #Final step:add shortcut value to main path and pass it through a relu activation
  x=Add()([x_shortcut,x])
  x=Activation('relu')(x)

  return x




In [ ]:
###########test whether the identity_block is working#############
from tensorflow.python.framework import ops
import tensorflow.compat.v1 as tfv
ops.reset_default_graph()
with tfv.compat.v1.Session() as test:
    A_prev = tfv.placeholder("float", [3, 4, 4, 6])
    X = np.random.randn(3, 4, 4, 6)
    A = identity_block(A_prev, f = 1, filters = [2, 4, 6], stage = 1, block = 'a')
    test.run(tfv.global_variables_initializer())
    out = test.run([A], feed_dict={A_prev: X, K.learning_phase(): 0})
    print("out = ", out[0][1][1][0])

out =  [0.74347335 1.3277023  0.         0.         0.         1.0553493 ]


In [ ]:
def convolutional_block(x,f,filters,stage,block,s=2):
  conv_name_base='res'+str(stage)+block+'_branch'
  bn_name_base='bn'+str(stage)+block+'_branch'
  #retrieve the filters
  f1,f2,f3=filters
  #save the input data
  x_shortcut=x
  ############### main path ################
  #first component of main path
  x=Conv2D(filters=f1,kernel_size=(1,1),strides=(s,s),
           name=conv_name_base+'2a',
           #The neural network needs to start with some weights and then iteratively update them 
           #to better values. The term kernel_initializer is a fancy term for which statistical 
           #distribution or function to use for initialising the weights.
           ##############################################
           #seed: A Python integer Used to seed the random generator.
           #seed: A Python integer An initializer created with a given seed will always produce 
           #the same random tensor for a given shape and dtype.
           kernel_initializer=glorot_uniform(seed=0))(x)
#If the dimension is [height, width, channel] then the axis is 3. The batch is not part of the input dimension. 
  x=BatchNormalization(axis=3,name=bn_name_base+'2a')(x)
  x=Activation('relu')(x)

#second component of main path
  x=Conv2D(filters=f2,kernel_size=(f,f),strides=(1,1),padding='same',
           name=conv_name_base+'2b',
           kernel_initializer=glorot_uniform(seed=0))(x)
  x=BatchNormalization(axis=3,name=bn_name_base+'2b')(x)
  x=Activation('relu')(x)

#third component of main path
  x=Conv2D(filters=f3,kernel_size=(1,1),strides=(1,1),padding='valid',
           name=conv_name_base+'2c',
           kernel_initializer=glorot_uniform(seed=0))(x)

  x=BatchNormalization(axis=3,name=bn_name_base+'2c')(x)

############# shortcut path ##############
  x_shortcut=Conv2D(filters=f3,kernel_size=(1,1),strides=(s,s),
                  name=conv_name_base+'1',
                  kernel_initializer=glorot_uniform(seed=0))(x_shortcut)
  x_shortcut=BatchNormalization(axis=3,name=bn_name_base+'1')(x_shortcut)

########final path##########
  x=Add()([x,x_shortcut])
  x=Activation('relu')(x)
  return x



In [ ]:
###########test whether the convolutional_block is working#############
from tensorflow.python.framework import ops
import tensorflow.compat.v1 as tfv
ops.reset_default_graph()
with tfv.Session() as test:
    A_prev = tfv.placeholder("float", [3, 4, 4, 6])
    X = np.random.randn(3, 4, 4, 6)
    A = convolutional_block(A_prev, f = 2, filters = [2, 4, 6], stage = 1, block = 'a')
    test.run(tfv.global_variables_initializer())
    out = test.run([A], feed_dict={A_prev: X, K.learning_phase(): 0})
    print("out = ",out[0][1][1][0])

out =  [0.        0.        0.        1.5865114 0.        0.       ]


In [ ]:
def ResNet50(input_shape=(64,64,3),classes=2):
  x_input=Input(input_shape)
  #Zero-paddng
  x=ZeroPadding2D((3,3))(x_input)

  #stage:1
  x=Conv2D(filters=64,kernel_size=(7,7),strides=(2,2),name='conv1',
           kernel_initializer=glorot_uniform(seed=0))(x)
  x=BatchNormalization(axis=3,name='bn_conv1')(x)
  x=Activation('relu')(x)
  x=MaxPooling2D(pool_size=(3,3),strides=2)(x)

  #stage:2
  x=convolutional_block(x,f=3,filters=[64,64,256],stage=2,block='a',s=1)
  x=identity_block(x,f=3,filters=[64,64,256],stage=2,block='b')
  x=identity_block(x,f=3,filters=[64,64,256],stage=2,block='c')

  #stage:3
  x=convolutional_block(x,f=3,filters=[128,128,512],stage=3,block='a',s=2)
  x=identity_block(x,f=3,filters=[128,128,512],stage=3,block='b')
  x=identity_block(x,f=3,filters=[128,128,512],stage=3,block='c')
  x=identity_block(x,f=3,filters=[128,128,512],stage=3,block='d')

  #stage:4
  x=convolutional_block(x,f=3,filters=[256,256,1024],stage=4,block='a',s=2)
  x=identity_block(x,f=3,filters=[256,256,1024],stage=4,block='b')
  x=identity_block(x,f=3,filters=[256,256,1024],stage=4,block='c')
  x=identity_block(x,f=3,filters=[256,256,1024],stage=4,block='d')
  x=identity_block(x,f=3,filters=[256,256,1024],stage=4,block='e')
  x=identity_block(x,f=3,filters=[256,256,1024],stage=4,block='f')

  #stage:5
  x=convolutional_block(x,f=3,filters=[512,512,2048],stage=5,block='a',s=2)
  x=identity_block(x,f=3,filters=[512,512,2048],stage=5,block='b')
  x=identity_block(x,f=3,filters=[512,512,2048],stage=5,block='c')
  
  #AVGPooling
  x=AveragePooling2D(pool_size=(2,2),name='avg_pool')(x)
 
  #output layer
  x=Flatten()(x)
  x=Dense(classes,activation='softmax',kernel_initializer=glorot_uniform(seed=0))(x)

  #create model
  model = Model(inputs = x_input, outputs = x)
  return model

############ all the function at a image ######################
#################plot_model(xception, to_file='model.png', show_shapes=True, show_layer_names=True)#################################

In [ ]:
#call the ResNet50
model=ResNet50(input_shape=(rows,cols,channels),classes=classes)



In [ ]:
model.compile(loss='categorical_crossentropy',
             #loss_weights={'main':1},
             optimizer='adam',
             metrics=['accuracy']
             )
    

In [ ]:
model.summary()

Model: "model_8"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_25 (InputLayer)           [(None, 64, 64, 3)]  0                                            
__________________________________________________________________________________________________
zero_padding2d_12 (ZeroPadding2 (None, 70, 70, 3)    0           input_25[0][0]                   
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 32, 32, 64)   9472        zero_padding2d_12[0][0]          
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, 32, 32, 64)   256         conv1[0][0]                      
____________________________________________________________________________________________

In [ ]:
#plot_model(mobile_net, to_file='model.png', show_shapes=True, show_layer_names=True)

In [ ]:
#train the model
model.fit(
    x_train,
    y_train,
    epochs=3,
    batch_size=64
)

Epoch 1/3
16/16 [==============================] - 151s 9s/step - loss: 0.6892 - accuracy: 0.7973
Epoch 2/3
16/16 [==============================] - 146s 9s/step - loss: 0.6734 - accuracy: 1.0000
Epoch 3/3
16/16 [==============================] - 147s 9s/step - loss: 0.6580 - accuracy: 1.0000


In [ ]:
preds = model.evaluate(x_test, y_test)

16/16 [==============================] - 8s 409ms/step - loss: 0.6075 - accuracy: 1.0000
